/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "housing" }],
  visaSidebar: [
    {
      type: "category",
      label: "English",
      link: { type: "generated-index" },
      collapsed: false,
      items: [
        "visa/en/quickstart",
        "visa/en/arc",
        "visa/en/documents",
        "visa/en/supplemental_documents",
        "visa/en/photo_id",
        "visa/en/fingerprint",
        "visa/en/payment_refund",
        "visa/en/video_tutorial",
      ],
    },
    {
      type: "category",
      label: "Korean",
      link: { type: "generated-index" },
      collapsed: false,
      items: [
        "visa/ko/quickstart",
        "visa/ko/arc",
        "visa/ko/documents",
        "visa/ko/supplemental_documents",
        "visa/ko/photo_id",
        "visa/ko/fingerprint",
        "visa/ko/payment_refund",
      ],
    },
  ],
  beddingSidebar: [{ type: "autogenerated", dirName: "bedding" }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
